name: Fetch Slack User Info

on:
  workflow_dispatch: # 사용자가 수동으로 실행할 수 있도록 설정

jobs:
  fetch-user-info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Node.js 버전을 설정합니다.

    - name: Install dependencies
      run: npm install

    - name: Generate Environment Variables File
      env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        FRONT_CHANNEL_ID: C078E953L9W
      run: |
        echo "SLACK_API_TOKEN=${{ secrets.SLACK_API_TOKEN }}" > .env
        echo "FRONT_CHANNEL_ID=${{ env.FRONT_CHANNEL_ID }}" >> .env

    - name: Run JavaScript
      run: node .github/scripts/get_slack_user_info.js

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .github/json/slackUserInfo.json
        git commit -m "refactor(slackUserInfo.json): $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.AREUM_GITHUB_TOKEN }}