name: PR 리뷰어 알림

on:
  pull_request:
    branches: [ main ]
    types: [ opened ]

# needs: [node@16]

jobs:
  notify-reviewers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

        with:
      - name: Get PR reviewer information
        id: get-reviewer-info
        uses: actions/github-script@v7
        with:
          script-path: .github/scripts/get-pr-reviewer-info.js
          # token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Get Reviewers List
      #   id: reviewers
      #   uses: actions/github-script@v7
      #   with:
      #     script: 
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   issue_number: ${{ github.event.pull_request.number }}
        #   reviewers: ${{ steps.reviewers.outputs.reviewers }}

      - name: Notify Reviewers with JS
        run: |
          node .github/scripts/pr_noti.js ${{ steps.reviewers.outputs.reviewers }} ${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}
        #   node .github/scripts/pr_noti.js ${{ steps.reviewers.outputs.reviewers }} ${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}
