# name: PR 리뷰어 알림

# on:
#   pull_request:
#     branches: [ main ]
#     types: [ opened ]

# # needs: [node@16]

# jobs:
#   notify-reviewers:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Get PR reviewer information
#       #   id: get-reviewer-info
#       #   run: node .github/scripts/get-pr-reviewer-info.js
#         uses: actions/github-script@v7
#         with:
#           script: |
#             const script = require(.github/scripts/get-pr-reviewer-info.js)
#             await script({ github, context, core })
            
#           # token: ${{ secrets.GITHUB_TOKEN }}

#       # - name: Get Reviewers List
#       #   id: reviewers
#       #   uses: actions/github-script@v7
#       #   with:
#       #     script: 
#         #   github_token: ${{ secrets.GITHUB_TOKEN }}
#         #   issue_number: ${{ github.event.pull_request.number }}
#         #   reviewers: ${{ steps.reviewers.outputs.reviewers }}

#       - name: Notify Reviewers with JS
#         run: |
#           node .github/scripts/pr_noti.js ${{ steps.reviewers.outputs.reviewers }} ${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}
#         #   node .github/scripts/pr_noti.js ${{ steps.reviewers.outputs.reviewers }} ${{ github.event.pull_request.title }} ${{ github.event.pull_request.html_url }}

name: slack_notice

on: 
  pull_request:
    types:
      - review_requested

jobs:
  notice:
    runs-on: ubuntu-18.04
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
