name: slack_notice

on: 
  pull_request:
    types: [ opened ]

jobs:
  notice:
    runs-on: ubuntu-latest
    steps:
      - name: action-slack-test
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action Test # default: 8398a7@action-slack
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() 
  