name: slack_notice

on: 
  pull_request:
    types: [review_requested, closed]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  slackNotice:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('./package-lock.json') }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
  
      - name: Generate Environment Variables File
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          echo "SLACK_API_TOKEN=$SLACK_API_TOKEN" >> .env

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

      - name: Run JavaScript
        run: | 
          node .github/scripts/get_pr_reviewer_info.js
