name: slack_notice

on: 
  pull_request:
    types: [ opened, closed, reopened, review_requested, review_request_removed, assigned]

jobs:
  notice:
    runs-on: ubuntu-latest
    steps:
      - name: action-slack-test
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action Test # default: 8398a7@action-slack
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: '추가된 텍스트'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() 
  


# >> pull_request 이벤트 목록

# opened: 새로운 풀 리퀘스트가 오픈되었을 때 발생합니다.
# synchronize: 풀 리퀘스트가 업데이트되었을 때 발생합니다. 이는 브랜치가 업데이트되거나 컴파일이 다시 실행되거나 파일이 변경된 경우를 포함합니다.
# closed: 풀 리퀘스트가 닫혔을 때 발생합니다.
# reopened: 닫힌 풀 리퀘스트가 다시 오픈되었을 때 발생합니다.
# edited: 풀 리퀘스트의 제목이나 설명이 편집되었을 때 발생합니다.
# review_requested: 풀 리퀘스트에 대한 리뷰가 요청되었을 때 발생합니다.
# review_request_removed: 풀 리퀘스트에 대한 리뷰 요청이 제거되었을 때 발생합니다.
# labeled: 풀 리퀘스트에 새로운 레이블이 추가되었을 때 발생합니다.
# unlabeled: 풀 리퀘스트에서 레이블이 제거되었을 때 발생합니다.
# assigned: 풀 리퀘스트에 새로운 담당자가 지정되었을 때 발생합니다.
# unassigned: 풀 리퀘스트에서 담당자가 할당 해제되었을 때 발생합니다.
# merged: 풀 리퀘스트가 머지되었을 때 발생합니다.
# pull_request_review: 풀 리퀘스트에 대한 리뷰가 제출되었을 때 발생합니다.
# status_updated: 풀 리퀘스트의 상태가 업데이트되었을 때 발생합니다.
# head_ref_deleted: 풀 리퀘스트의 기준 브랜치가 삭제되었을 때 발생합니다.
# marketplace_purchase: 풀 리퀘스트에서 GitHub Marketplace 앱을 구매했을 때 발생합니다.